### ISSUE TITLE
Sharing and families/teams/enterprise features

### ISSUE THREAD

**Issue by beatgammit** [jcs/rubywarden#5]
I didn't see anywhere on your project where you discussed how sharing passwords works in a self hosted environment. I'm interested in using an alternative to the official .NET application, and your project is the one that I found first.

Are you interested in supporting the non-free tier features (at least sharing)? If not, perhaps I'll try it on my own (I'm not a fan of Ruby, so it'll probably be in Go or Rust). If it's something you're interested in, I could look into it and perhaps submit a PR or something (no guarantees).

Personally, I'm most interested in the sharing feature, but I'm not sure how that's being handled or how the official Bitwarden servers come into play. To be clear, I'm not looking to avoid paying Bitwarden, I just don't want the .NET server code.

**Comment by jcs** [comment]
I don't have any personal interest in it because I'm the only user of my instance, but I'm not opposed to merging such support if it was implemented cleanly.

There are `Organizations` and `OrganizationId` in the [API](https://github.com/jcs/bitwarden-ruby/blob/master/API.md) output so I'm assuming there's just an `Organization` object that `Cipher` objects can belong to (like `Folder` objects).  I haven't looked at how organizations are implemented in the official Bitwarden code bases, but I'd guess there's an API call for assigning a `Cipher` object to an `Organization` which then makes it visible to everyone in the `Organization` in the `/sync` call.  I don't know if there are any permission levels on them that controls who can view vs. edit, or how a user actually gets joined to a team.

**Comment by feld** [comment]
I would love this as well.

**Comment by Pschittt** [comment]
@jcs From what I saw, there is indeed Organizations, which regroup users.
The relationship between Organization and Cipher, is made via Collection and a CollectionCipher object.

In your API, it needs to add several database tables : 
- "Organization" with (at least) these columns "Id", "Name", "BusinessName", "BillingEmail", "Plan" 
- "OrganizationUser" with (at least) these columns "Id, "OrganizationId", "UserId"
- "Group" with (at least) these columns "Id", "OrganizationId", "Name"
- "GroupUser" with (at least) these columns "GroupId", "OrganizationUserId"
- "Collection" with (at least) these columns "Id", "OrganizationId", "Name", "CreationDate", "RevisionDate"
- "CollectionGroup" with (at least) these columns  "CollectionId", "GroupId", "ReadOnly"
- "CollectionCipher" with (at least) these columns "CollectionId", "CipherId" (which reference to Cipher table)
- "CollectionUser" with (at least) these columns  "CollectionId", "OrganizationID", "ReadOnly"

Well, I don't know how to translate this into the ruby code :)

**Comment by andrzejwp** [comment]
I'm not a Ruby person either, but I would sure love this feature. Maybe @logic could help?

**Comment by logic** [comment]
I'm afraid I'm mostly in the same boat as @jcs, I don't really have any personal need for any of the sharing/organization stuff, so it's probably not something I'll end up spending a ton of time on, at least not right now.

**Comment by beatgammit** [comment]
I haven't done Ruby in years, but maybe I'll take a crack at it. That's not a promise in any sense though.

**Comment by Odysseus16** [comment]
If you would like more information about the Organization feature, you can visit the [my](https://github.com/Odysseus16/bitwarden-go) repository 
(it's written in go). I have implemented it, and as soon as I have time I will update jcs great API.
